version: "3"

services:
  app:
    build:
      context: .
    container_name: test_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.envs:/envs
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.envs/.env
  db:
    image: my-postgres-image
    container_name: test_app_db
    ports:
      - '5555:5432'
