version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: my-python-image
    container_name: test_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: bash -c
      "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis
      - rabitmq
    restart: on-failure # always
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}

  celery:
    image: my-python-image
    container_name: test_app_celery
    command: celery -A app worker -P prefork -c 4 -l info
    volumes:
    - ./app:/app
    depends_on:
      - redis
      - rabitmq
    restart: on-failure

  db:
    build:
      context: ./pgs
      args:
        psql_pass: ${DB_PASSWORD}
        psql_db: ${DB_NAME}
      dockerfile: Dockerfile-psql
    image: my-postgres-image
    container_name: test_app_db
    ports:
      - '5555:5432'
    restart: on-failure

  redis:
    image: redis
    container_name: some-redis
    ports:
    - '6379:6379'
    restart: on-failure

  rabitmq:
    image: rabbitmq:3-management
    container_name: some-rabbitmq
    ports:
    - '15672:15672'
    - '5672:5672'
    restart: on-failure